Première page concernant la compilation sur macos.
Section-IG/wiki pull request #5
Opened 2021-11-22 22:10 UTC by Etu4943

Bon alors j'ai fini ma première page. En revanche je n'ai apparement pas les accès pour faire un git push -u origin clemIG1. Soit. VSCode ma proposé de réer un "fork" et apparement je peux avec ceci faire un pull request. Vous me direz si ça fonctionne et si c'est une bonne manière de faire ou pas du tout. 

Hâte d'avoir de vos retour et de contribuer a ce wiki !

2021-11-25 23:49 UTC, HunteRoi requested changes
Hey @Etu4943 !

Bienvenue sur Github :smile: Tu peux commencer par aller dans tes préférences utilisateur (en haut à droite sur Github web) et t'assigner un pseudo plus parlant que ton matricule étudiant. Ca rendra nos conversations plus agréables!

Concernant ta pull request, voici mes retours sous forme de commentaires "inline" dans tes fichiers. J'ai tout de même une question: **as-tu lu et compris ceci: https://docusaurus.io/docs/markdown-features ?**

De manière globale, le travail est bien réalisé mais attention :warning: :
- **ne rajoute pas le fichier PDF sur GitHub.** C'est lourd, et ça prend de la place inutilement. Stocke-le ailleurs, et utilise un lien vers la ressource externe pour le consulter/télécharger 😉 
- **nomme tes fichiers d'une manière plus compréhensible!** "ClemIG1_recap.png", ça ne signife rien pour moi. Je propose que tu le renommes avec un nom plus parlant, en lien avec le titre de ta page de documentation.
- **tu as publié un yarn.lock modifié.** Cela ne fait pas partie du sujet de ta PR, pourtant. Peux-tu le retirer svp?
- **le ton employé dans ta page de documentation** doit correspondre au ton employé partout ailleurs. Il serait bon de discuter de comment l'on devrait s'adresser aux autres. Par exemple, est-il plus intéressant de s'adresser aux lecteurs avec des "tu" ou avec des "vous". Faut-il également avoir un langage plus large (dans le sens "je parle à des gens qui ne comprennent pas forcément l'informatique") ou non? Je te laisse avancer tes arguments en commentaire 💬 
- **n'hésite pas à ajouter des images** afin que les lecteurs vérifient visuellement leur démarche. C'est ce qui marche le mieux dans les tutos 😃 

**Quand tu auras revu et fais les changements nécessaires, peux-tu demander ma review à nouveau?** Je lancerai localement la solution avec tes changements pour voir le rendu visuel afin de regarder si l'on peut l'améliorer. Cependant, n'hésite pas à faire une capture d'écran et à l'ajouter à la description de ta PR!

Encore merci pour ta participation! 💯

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +Si jamais vous désirez télécharger le pdf : [CompilerMac.pdf](../../static/pdf/Compiler_mac.pdf)
Je noterais cette information soit en tant que disclaimer, soit en fin de page dans une partie "conclusion"

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +Vous aurez vite remarqué que toutes les commandes vues en cours ne sont pas toutes valides sur votre mac.
À mon sens, "mac" est un nom propre et devrait donc s'orthographier comme tel (avec une majuscule quoi)

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +
Ca serait sympa d'avoir un sommaire ou une liste des commandes que tu vas aborder au lieu de débuter de but en blanc, non? Et peut-être une explication plus concise de pourquoi cet article est écrit. 

Qu'en penses-tu?

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +**- Ouvrir le terminal via spotlight** :mag_right: :
ne mets pas de `:` après un titre

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +A noter que ici "tableau" sera le nom donné à notre fichier "éxécutable". (Abus de language). On peut evidemment choisir de l'appeler comme on veut.
Cela s'écrit "exécutable" si jamais! Tu peux également laisser tomber les parties entre parenthèses si elles n'apportent rien d'intéressant à l'ensemble du document écrit.
Par ailleurs, tu as oublié un accent sur le é de "évidemment" ^^

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +Pour terminer, la commande pour lancer notre code une fois copiler :
```suggestion
Pour terminer, voici la commande pour exécuter le code une fois compilé:
```

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +
```suggestion
:::tip Petit conseil d'utilisation

Puisque l'on recompile énormément de fois le même code, gardez toujours le même nom de sortie! Cela permettra d'écraser le fichier précédent et d'avoir **un seul fichier** exécutable à jour.

:::
```

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +Pour commencer il faudra évidemment retrouver le chemin d'accès de votre fichier.c .
```suggestion
Pour commencer, il faudra évidemment retrouver le chemin d'accès de votre `fichier.c`.
```

2021-11-25 23:49 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +Si sur windows cela fonctionne avec Visual Studio 2019 et la commande cl, ici c'est un petit peu plus complexe, bien qu'en contrepartie on ai rien à installer !
Windows est un nom de marque, et donc un nom propre. Comme "Visual Studio", il doit prendre une majuscule.

```suggestion
Si, sur Windows, cela fonctionne avec Visual Studio et la commande `cl`, ici, c'est un petit peu plus complexe... bien qu'en contrepartie, on ait rien à installer !
```

2021-11-26 00:09 UTC, Etu4943 commented on docs/ClementIG1_test/windowsToMac.md
> +Si jamais vous désirez télécharger le pdf : [CompilerMac.pdf](../../static/pdf/Compiler_mac.pdf)
Justement, c'est une solution rapide que je pensais facile d'accès. --> Ceux qui viennent expressément chercher ce document. Voilà pourquoi je l'ai mis au début. 
Je tâche de le mettre en fin alors !

2021-11-26 00:15 UTC, Etu4943 commented on docs/ClementIG1_test/windowsToMac.md
> +
J'en pense que, et c'est purement personnel comme ressenti, j'aime quand les informations que je cherche vont droit au but et qu'écrire un pavé perdrait peut-être les élèves qui tente de trouver une informations précise dans un long article. Sincèrement juste un tableau avec des tirets serait clair, net et précis mais c'est moins convivial. 
Maintenant je commente tout vos commentaire comme si je détenait la vérité absolu et j'en suis désole ce n'est absolument pas le but. N'est-pas "parasite" d'expliquer mes raisons ?

2021-11-26 00:20 UTC, Etu4943 commented on docs/ClementIG1_test/windowsToMac.md
> +A noter que ici "tableau" sera le nom donné à notre fichier "éxécutable". (Abus de language). On peut evidemment choisir de l'appeler comme on veut.
Je note !

2021-11-27 23:27 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +Si jamais vous désirez télécharger le pdf : [CompilerMac.pdf](../../static/pdf/Compiler_mac.pdf)
Tu peux le mettre au début en utilisant une admonition de type "info" par exemple, hein! https://docusaurus.io/docs/markdown-features/admonitions

2021-11-27 23:29 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +
Si tu cherches une information précise, tu lis en diagonale ou tu fais un `Ctrl+F`. Ici, il s'agit d'être à la fois explicite, informatif mais aussi descriptif. Il faut pouvoir contenter tout le monde! Tu n'es pas obligé d'écrire un pavé (et ce n'est pas ce que j'ai demandé) mais tu peux faire des phrases plus conviviales 😄

2022-01-15 23:35 UTC, HunteRoi commented on docs/ClementIG1_test/windowsToMac.md
> +![recap](../../static/img/ClemIG1_recap.png)
Tu peux faire un tableau en markdown. Je conseille d'ailleurs ce générateur: https://www.tablesgenerator.com/markdown_tables

2022-03-23 16:09 UTC, DrakeXorn commented
@Etu4943 Tu peux faire les changements dont @HunteRoi a parlés s'il te plaît ? 🙂  Mettre "👍 " en réaction aux messages ne change pas ton code 😬 

Aussi, j'ai une petite remarque à faire concernant le dossier dans lequel tu as écrit ton fichier Markdown... "ClementIG1_test", c'est pas super au niveau compréhension de ce qui se trouve dedans. Surtout quand on le voit s'afficher sur la page du wiki 😬  "Compilation sous MacOS" serait peut-être une meilleure façon de nommer le dossier, mais libre à toi de trouver une autre dénomination 😄

2022-03-27 23:10 UTC, merged